import "@/css/global.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/ui/Header";
import { AppContextProvider } from "@/contexts/app.contexts";
import { NextAuthProvider } from "@/utils/next-auth/next-auth-providers";
import ReactQueryProviders from "@/utils/react-query/react-query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-full">
          <ReactQueryProviders>
            <AppContextProvider>
              <NextAuthProvider>
                <Header />
                {children}
              </NextAuthProvider>
            </AppContextProvider>
          </ReactQueryProviders>
        </div>
      </body>
    </html>
  );
}
